version: "2"
services:
    client:
        build: ./multitenancyclient
        ports:
            - "4200:4200"
        depends_on:
            - web
    web:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - acme
            - loreal
    acme:
        build: ./dockerscripts/acme/ 
        environment:
            SA_PASSWORD: "catuser@123"
            ACCEPT_EULA: "Y"
    loreal:
        build: ./dockerscripts/loreal 
        environment:
            SA_PASSWORD: "catuser@123"
            ACCEPT_EULA: "Y"
